remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Alisha's World
theme: jekyll-theme-minimal
description: A portfolio of my work! Keep an eye out on what's to come in 2025!


